-- MySQL Script generated by MySQL Workbench
-- Wed May 24 19:56:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SafeWallet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SafeWallet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SafeWallet` DEFAULT CHARACTER SET utf8 ;
USE `SafeWallet` ;

-- -----------------------------------------------------
-- Table `SafeWallet`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeWallet`.`User` (
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeWallet`.`CountType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeWallet`.`CountType` (
  `idType` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `TaxRate` DOUBLE NULL,
  PRIMARY KEY (`idType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeWallet`.`Countt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeWallet`.`Countt` (
  `CountNum` VARCHAR(10) NOT NULL,
  `mount` DOUBLE NULL,
  `idType` INT NULL,
  `InitDate` DATE NULL,
  PRIMARY KEY (`CountNum`),
  INDEX `type_idx` (`idType` ASC),
  CONSTRAINT `type`
    FOREIGN KEY (`idType`)
    REFERENCES `SafeWallet`.`CountType` (`idType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeWallet`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeWallet`.`Person` (
  `RFC` VARCHAR(50) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `PhoneNum` VARCHAR(10) NULL,
  `CountNum` VARCHAR(10) NULL,
  `PublicKey` VARBINARY(700) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`RFC`),
  INDEX `email_idx` (`email` ASC),
  INDEX `count_idx` (`CountNum` ASC),
  CONSTRAINT `email`
    FOREIGN KEY (`email`)
    REFERENCES `SafeWallet`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `count`
    FOREIGN KEY (`CountNum`)
    REFERENCES `SafeWallet`.`Countt` (`CountNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeWallet`.`OpType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeWallet`.`OpType` (
  `id` INT NOT NULL,
  `Name` VARCHAR(50) NULL,
  `Description` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeWallet`.`Operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeWallet`.`Operation` (
  `idOp` INT NOT NULL AUTO_INCREMENT,
  `typeOp` INT NULL,
  `date` DATETIME NULL,
  `mount` DOUBLE NULL,
  `count` INT NULL,
  PRIMARY KEY (`idOp`),
  INDEX `typeOp_idx` (`typeOp` ASC),
  INDEX `count_idx` (`count` ASC),
  CONSTRAINT `typeOp`
    FOREIGN KEY (`typeOp`)
    REFERENCES `SafeWallet`.`OpType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `count`
    FOREIGN KEY (`count`)
    REFERENCES `SafeWallet`.`Countt` (`CountNum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeWallet`.`logOp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeWallet`.`logOp` (
  `idlogOp` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NULL,
  `Desc` VARCHAR(100) NULL,
  PRIMARY KEY (`idlogOp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SafeWallet`.`LogBook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeWallet`.`LogBook` (
  `Date` DATETIME NOT NULL,
  `Operation` INT NULL,
  `User` VARCHAR(50) NULL,
  PRIMARY KEY (`Date`),
  INDEX `userLog_idx` (`User` ASC),
  INDEX `LogOp_idx` (`Operation` ASC),
  CONSTRAINT `LogUser`
    FOREIGN KEY (`User`)
    REFERENCES `SafeWallet`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `LogOp`
    FOREIGN KEY (`Operation`)
    REFERENCES `SafeWallet`.`logOp` (`idlogOp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `SafeWallet`.`CountType`
-- -----------------------------------------------------
START TRANSACTION;
USE `SafeWallet`;
INSERT INTO `SafeWallet`.`CountType` (`idType`, `Name`, `TaxRate`) VALUES (1, 'GOLD', 0.01);
INSERT INTO `SafeWallet`.`CountType` (`idType`, `Name`, `TaxRate`) VALUES (2, 'SILVER', 0.05);
INSERT INTO `SafeWallet`.`CountType` (`idType`, `Name`, `TaxRate`) VALUES (3, 'BRONZE', 0.1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `SafeWallet`.`Countt`
-- -----------------------------------------------------
START TRANSACTION;
USE `SafeWallet`;
INSERT INTO `SafeWallet`.`Countt` (`CountNum`, `mount`, `idType`, `InitDate`) VALUES ('123456789', 0.0, 1, '2016-02-01');
INSERT INTO `SafeWallet`.`Countt` (`CountNum`, `mount`, `idType`, `InitDate`) VALUES ('213456789', 50000.21, 2, '2015-01-01');

COMMIT;

